// <auto-generated />
namespace CaloryCounterProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CrDto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrDto));
        
        string IMigrationMetadata.Id
        {
            get { return "202103082141335_Cr-Dto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
